### ISSUE TITLE
Alt+Enter not working / strange behavior

### ISSUE THREAD

**Issue by DissCent** [dukope/BugsPlease#10]
Usually, when pressing Alt+Enter in games, the game switches between windowed and fullscreen mode. So I started the game in windowed mode and pressed Alt+Enter - the screen flashes black for a really short time and returns back to the desktop without changing the window mode.

EDIT: Maybe it's also not planned to be a feature, but either way, something is happening - just not right ;-)

Profile:
openSUSE 13.1 x64
NVidia graphics 331.38 (GeForce 760 GTX)

**Comment by dukope** [comment]
Does toggling the Fullscreen option in the settings menu work ok?

(Alt-Enter is supposed to work, sounds like a bug)

**Comment by DissCent** [comment]
Yeah, using the options works flawlessly.

**Comment by dukope** [comment]
Phew. That's probably a bug I can fix then.

**Comment by Tailszefox** [comment]
Just to confirm, same issue here. This leads to this kind of odd thing, if I press Alt+Enter multiple times and then use the menu:

![papers4](https://f.cloud.github.com/assets/890677/2052047/85314972-8a91-11e3-99b7-28e739f4cc74.png)

(Fullscreen checked, yet the game is in a window).

Launching the game with the "Software Rendering" option leads to the same issue.

Hardware:
Linux Mint LMDE (Debian Wheezy)
Intel Integrated graphics (I can't seem to find the actual model for some reason)

**Comment by dukope** [comment]
Found the bug. I'm manually catching Alt+Enter and toggling fullscreen/windowed myself. OpenFL also handles this automatically on Linux so it was getting applied twice. Will fix.

**Comment by dukope** [comment]
Fixed in 1.1.56
