### ISSUE TITLE
German localization - "regulations" typing error

### ISSUE THREAD

**Issue by DissCent** [dukope/BugsPlease#11]
In the German localization, there's an error on the title of the "Ministry of Admission - Rules and Regulations" book.
"Regulations" have been translated to "Regularieren" which should be "Regularien" instead (see screenshot below).

By the way, should all typing errors/localization issues be collected into a single issue or should we open a single issue each time?

![papersplease1](https://f.cloud.github.com/assets/1782508/2051735/ad0bb012-8a8d-11e3-8162-9e264e368234.png)

**Comment by dukope** [comment]
Good question. ~~Let's put all per-language loc errors in a single issue. That'll make it easier to pass them by the localizers. This'll be the issue for German loc errors.~~

Actually on second thought, just open an new issue for each one. I'm too scared to try to coordinate putting everything in one issue. And if they're separate then I can close them as they get fixed; one by one.

**Comment by dukope** [comment]
Fixed in 1.1.56
