### ISSUE TITLE
Rendering issue on fingerprint information paper (German/Linux)

### ISSUE THREAD

**Issue by DissCent** [dukope/BugsPlease#12]
When checking fingerprints, the information that pops up has a rendering issue on the name of the immigrating person (see above the mouse pointer):

![papersplease2](https://f.cloud.github.com/assets/1782508/2051856/4a8200a2-8a8f-11e3-9ab3-6ebb4d0b3769.png)

I'm not sure if it's the platform or the language, maybe I can find this out later by switching the language.

Profile:
openSUSE Linux 13.1 x64
 NVidia graphics 331.38 (GeForce 760 GTX)

**Comment by dukope** [comment]
This is by design :) Bad design maybe, but intentional. It's supposed to represent a faulty dot-matrix printer which the Ministry is too cheap to replace.
