### ISSUE TITLE
Slow loading times on some documents

### ISSUE THREAD

**Issue by DissCent** [dukope/BugsPlease#13]
I've experienced some loading delay on some of the documents that persons give you. Best example is the letter table that EZIC gives you on 1st Dec (the black document on which you put another later and it highlights some letters - I hope that describes it).
When opening this document by double click, the game hangs for ~5 seconds, you can't even move your mouse.

Usually, I'd blame a slow system for high loading times, but I have a quad-core CPU with an SSD.

I'm using German language.

Profile:
openSUSE Linux 13.1 x64
NVidia graphics 331.38 (GeForce 760 GTX)

**Comment by dukope** [comment]
Is it consistently the same documents? Long pauses make me think it could be the garbage collector, but that'd show up fairly randomly.

**Comment by DissCent** [comment]
Okay, actually it seems I can't reproduce it. When it originally happened, the game was already running for more than an hour so I guess you're right about the garbage collection - sorry!

**Comment by dukope** [comment]
I'll close this for now, but it's a legitimate problem. I'll come back and look at it after the update.
