### ISSUE TITLE
[German localization] Counter->Zähler should be Counter->Tresen

### ISSUE THREAD

**Issue by ghost** [dukope/BugsPlease#16]
![zhler](https://f.cloud.github.com/assets/100837/2057919/ff33d8ca-8b54-11e3-969c-8ae7a46f9988.png)

Translated counter like in "to count". Should be "Tresen" instead.

**Comment by dukope** [comment]
Nice catch. The rulebook page correctly has "Tresen". 

(You can include pics directly in the issue comment by dragging and dropping them in the box)

**Comment by ghost** [comment]
> (You can include pics directly in the issue comment by dragging and dropping them in the box)

Will do.

**Comment by dukope** [comment]
Fixed in 1.1.57
