### ISSUE TITLE
French localization - Citation text gets cut off with too many errors

### ISSUE THREAD

**Issue by Tailszefox** [dukope/BugsPlease#17]
![papers5](https://f.cloud.github.com/assets/890677/2058099/e3a46c6a-8b5d-11e3-8dfc-07aa1941943b.png)

In this example, the photo on the passport wasn't a photo of the immigrant, so I made a fingerprint test. The fingerprints didn't match either. But in any case, I let the person in, and that, of course, resulted in a citation.
The issue is that the last sentence gets cut off probably because of a lack of space. It says "Empreintes différentes de celles" which translates to "Fingerprints different than", with the end of the sentence not shown.

I don't know if there's a way to either make the citation paper bigger, reduce the size of the sentence (the sentence for the photo takes two lines with the last word taking up the whole second line for itself), or only show one error instead of two to avoid this. The citation is still understandable however, it's just a bit confusing.

**Comment by dukope** [comment]
Hmm.. You have a good suggestion. I could replace the carriage returns between items with a dash or something, which would prevent that 3rd line from wasting so much space. That's a big change though so I'll have to think on it a bit.

What bothers me more is that the penalty line is way overflowing...

**Comment by Tailszefox** [comment]
Do you mean the line at the bottom saying "Dernier avertissement - Pas de pénalité"? I noticed it before, but since it wasn't overflowing outside of the actual paper, I thought that would be okay to let it be. Of course, if it's supposed to absolutely be kept between the two lines of dots, then yeah, it is overflowing quite a bit. I think a rephrasing or a reduction of the sentence (like "Dernier avert. - Pas de pénalité") could work, but that's just a suggestion.

**Comment by dukope** [comment]
Yeah, I've never seen a dot matrix printer that could put ink over the feed holes. :P

These are the lines used there:
AVERTISSEMENT - PAS DE PÉNALITÉ
DERNIER AVERTISSEMENT - PAS DE PÉNALITÉ
PÉNALITÉ INFLIGÉE - $0 CRÉDITS

Only the middle one is too long. I'll change it to "DERNIER AVERT. - PAS DE PÉNALITÉ". Thanks!

(This is not strictly the localizer's fault, since this string is not dimensioned in the loc tool. But I would've expected their playtesting to catch it.)

**Comment by Tailszefox** [comment]
Ooh, right. I admit I never saw an actual dot matrix printer...print, so that went way over my head. In that case, yeah, no way it could print there.

Anyway, glad that one is fixed, you're welcome!

**Comment by WordsOfMagic** [comment]
I did notice the overflowing, but like Tailszefox, I thought is would be OK for clarity's sake.
Maybe we could try ULTIME instead of DERNIER, not sure it would be enough though.

**Comment by dukope** [comment]
Unfortunately, ULTIME doesn't fit either. I'll use "DERNIER AVERT. - PAS DE PÉNALITÉ" unless you feel strongly otherwise.

**Comment by dukope** [comment]
I've figured out a reasonable solution for the missing line of text: The game will leave out the first line ("Protocol Violation") if the following (more important) lines need the space. 

It was already doing this based on the # of items, but it had no consideration if these items took more than one line of text. Now that I measure the actual line count it works better. The fix will be in the next build.

**Comment by Tailszefox** [comment]
That does sound much better, this line is nice to have but it's clearly not as important as having the rest of the items telling you what you actually missed. If it's impossible to make the paper longer in height, then removing this line like this seems like the best solution.

**Comment by dukope** [comment]
Fixed in 1.1.57
