### ISSUE TITLE
Russian Localization - First look bugs and issues

### ISSUE THREAD

**Issue by monodance** [dukope/BugsPlease#18]
I've made some screenshots of bugs I've seen.

Arstotzka passport bug. It seems that smaller font has to be used.
![papersplease 2014-02-01 22-54-28-67](https://f.cloud.github.com/assets/5888952/2058614/289ffc78-8b7a-11e3-83aa-a5b2f6a9dc5e.jpg)

In newspaper between day 4 and 5. 
![papersplease 2014-02-01 23-13-55-43](https://f.cloud.github.com/assets/5888952/2058621/7bd5fb0e-8b7a-11e3-8dc2-8ee17eade268.jpg)
Also, small titles here translated different.
'Politics'(original) removed with 'Погода' ('Forecast' or 'Weather' on russian).
'Sports'(original) removed with 'Развлечения' ('Entertainments' on russian).

**Comment by dukope** [comment]
The small titles with politics/weather/sports/entertainment are randomly selected and could be different on each play, so that's ok.

For the text replacement, can you type the text in here? I'm not good with Cyrillic but I can do a find/replace :)

(I'll fix the Arstotzka passport, thanks)

**Comment by monodance** [comment]
All right. It seems that "Lestrade" was just misstyped. In russian it's "Лестрейд".

**Comment by dukope** [comment]
Got it, thanks!

**Comment by dukope** [comment]
I'll leave this open until the fix is published in the next build.

**Comment by dukope** [comment]
Fixed in 1.1.57
