### ISSUE TITLE
Horizontal "lines" in fingerprint slip

### ISSUE THREAD

**Issue by ghost** [dukope/BugsPlease#19]
![stripes](https://f.cloud.github.com/assets/100837/2059032/d14dd21a-8b92-11e3-91f5-3d0052bb4595.png)

```
akurei@joel: ~ $ xrandr -q; uname -a ;yaourt -Qi kdebase-workspace xf86-video-intel linux xorg-server intel-dri |egrep -i "^(name|version).*"
Screen 0: minimum 320 x 200, current 3360 x 1200, maximum 8192 x 8192
LVDS1 connected primary 1440x900+0+0 (normal left inverted right x axis y axis) 304mm x 190mm
   1440x900       60.2*+   50.0  
   1024x768       60.0  
   800x600        60.3     56.2  
   640x480        59.9  
VGA1 connected 1920x1200+1440+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200      60.0*+
   1600x1200      60.0  
   1680x1050      60.0  
   1280x1024      75.0     60.0  
   1440x900       75.0     59.9  
   1280x960       60.0  
   1280x800       59.8  
   1152x864       75.0  
   1024x768       75.1     70.1     60.0  
   832x624        74.6  
   800x600        72.2     75.0     60.3     56.2  
   640x480        75.0     72.8     66.7     60.0  
   720x400        70.1  
DP1 disconnected (normal left inverted right x axis y axis)
Linux joel 3.12.9-2-ARCH #1 SMP PREEMPT Fri Jan 31 10:22:54 CET 2014 x86_64 GNU/Linux
Name           : kdebase-workspace
Version        : 4.11.5-1
Name           : xf86-video-intel
Version        : 2.99.908-1
Name           : linux
Version        : 3.12.9-2
Name           : xorg-server
Version        : 1.15.0-5
Name           : intel-dri
Version        : 10.0.2-1
```

**Comment by ErdmannOle** [comment]
See here: https://github.com/dukope/BugsPlease/issues/12.

**Comment by ghost** [comment]
Oh, I never thought this could be intentional. Afair I never saw that on the Windows version. Has this been added recently?

Also it's inconsistent: Shouldn't the warnings when you do something wrong (which are also printed) also show the "lines"?

Should I open a new bug about the inconsistent behaviour?

**Comment by dukope** [comment]
This effect has always been in the game. But the lines are randomized so you could go a while without noticing that they overlap the text.

It's only applied to the fingerprint slip. For consistency it should probably be applied to anything printed from the bottom of the screen. Or maybe even removed since it looks like a bug. But given the priorities I'll probably just leave it all as-is.
