### ISSUE TITLE
German Localization - Typos and Graphical Issues

### ISSUE THREAD

**Issue by ErdmannOle** [dukope/BugsPlease#20]
I played to the end of day 4 and here are some issues I could find.

1) In the rule book the word "Jalousie" is used, while the bulletin uses "Rolladen". While both words are correct I suggest using "Rollladen". Yes, it is correctly spelled with three "L".
And as someone mentioned earlier: "Zähler" must be replaced by "Tresen". The rule book is correct in this case.

![rollladen jalousie](https://f.cloud.github.com/assets/6563832/2059748/2ebd6bae-8bcf-11e3-94f9-9d2a8958b673.PNG)

2) In the bulletin it first says "Prüf-Modus" and on the next page it's "Prüfen-Modus". Both are alright but "Prüf-Modus" sounds a lot better. So use that one.

![pruf prufen](https://f.cloud.github.com/assets/6563832/2059757/dad08bb4-8bd0-11e3-85ce-c07adc397a69.PNG)

3) I don't know if this is a real issue but to me it looks like the stamp's "M" is not displayed correctly.

![pixelfehler stempel](https://f.cloud.github.com/assets/6563832/2059760/21af955c-8bd1-11e3-8cf3-ec796abde7e9.PNG)

4) This is actually a bigger one. All the bulletins that have been shown to this point have this issue so I reckon the others are faulty as well. In a letter the first word in the sentence after the comma must be in lower case if it's not a noun or some special instance. The word "Mit" in the picture must be in lower case.

In the following line the "ä" looks a bit like an "a" because the dots are in the same spot as the dotted line.

I'm not exactly sure if this is intentional or not, but according to the new spelling rules "Paß" is written with 2 "S" instead of "ß". It would make sense to write it the old way because the spelling rules haven't been changed until 1996. If you want to leave it as it is now "Pass-Daten" needs to be changed to "Paß-Daten".

![pass pa depesche 24 11](https://f.cloud.github.com/assets/6563832/2059764/4e40ad9a-8bd1-11e3-8613-bd9fae85fade.PNG)

5) Here the "N" is not displayed correctly.

![kolechien](https://f.cloud.github.com/assets/6563832/2059793/e877b8ec-8bd4-11e3-825c-be57ac9cbd75.PNG)

6) I suggest to use the word "all" instead of "alle". It simply sounds better.

![die rosa sunde](https://f.cloud.github.com/assets/6563832/2059794/099f19d4-8bd5-11e3-9d4d-a5903ea012db.PNG)

7) The little yellow thing at the bottom of some bulletins is a bit replaced so the arrow is not visible. The picture in the left corner shows the proper way.

![alle seiten](https://f.cloud.github.com/assets/6563832/2059797/2d490e76-8bd5-11e3-90b1-2fb9dd49f177.PNG)

And an additional suggestion:
You should consider adding a mute button for the music and the sounds in the menu. It is kinda annoying to press the button several times if you want it to be muted.

**Comment by dukope** [comment]
Great stuff. 3, 5, and 7 are mine. I'm asking the German localizer to take a look at the rest.

**Comment by ErdmannOle** [comment]
I just found another one. 

8) A comma is missing between "Arrest" and "bis".

![komma fehlt](https://f.cloud.github.com/assets/6563832/2059825/d622a96e-8bd8-11e3-84a1-fd6e227e2937.PNG)

By the way: it's not easy to look out for bugs and working fast enough to stay out of jail at the same time. ;)

**Comment by dukope** [comment]
> By the way: it's not easy to look out for bugs and working fast enough to stay out of jail at the same time. ;)

You're doing a pretty good job so far. :D 

Try turning on easy mode from the title settings menu for a little help! It has no other effect except to give you an extra 20 credits/day.

**Comment by ErdmannOle** [comment]
Got a new minor bug. The symbol in the lower right that appears when the audio transcripts text gets too long is slightly overlapping the text. Also, if I was on the second page of the audio transcript and put it back into the storage I'm immediately on the second page again when I open it at the following entrant. Then there is no text and as soon as I click on the button to go to the first page the button disappears and everything is normal again.

![uberlappt text](https://f.cloud.github.com/assets/6563832/2059950/aa350bf8-8bec-11e3-98f7-bd700caeb993.PNG)

**Comment by dukope** [comment]
@ErdmannOle, I'll try to move that next-page arrow down a few pixels to fix that. 

In the future, please open a new issue unless it's a clear extension of the original issue. With too many different bugs in one issue it gets harder to track, fix, and ultimately close. Thanks. :)

**Comment by ErdmannOle** [comment]
Ok, here comes a big update. I've tried to only include typos or graphical related issues.

I'll continue the first and second post's enumeration.

9) If the localizer wants to stick to the old German spelling rules „so weit“ needs to be changed to „soweit“ in the conversation with Jorji.

![so weit soweit](https://f.cloud.github.com/assets/6563832/2072949/7b59ac02-8d4b-11e3-92db-1f6cf8f28150.PNG)

10) At the end of day 5 the term „Prüfen-Modus“ is used again. See entry 2.

![prufen-modus 02](https://f.cloud.github.com/assets/6563832/2072968/ff10b2de-8d4b-11e3-9abf-4c306eef8f1b.PNG)

11) In this conversation on day 4 „haben“ has to be replaced by „habe“.

![haben habe](https://f.cloud.github.com/assets/6563832/2072979/5be09222-8d4c-11e3-9d24-b653279a30d5.PNG)

12) In the conversation with Vince Lestrade „dieses“ has to be replaced by „diesen“.

![dieses diesen](https://f.cloud.github.com/assets/6563832/2072985/96469808-8d4c-11e3-9477-9b1c10d11297.PNG)

13) In the newspaper of December 6th the word „Verräter“ is seperated wrong. It should be „Ver-rä-ter“ instead of „Ver-rät-er“. On December 15th it's seperated correctly.

![verrat-er verra-ter](https://f.cloud.github.com/assets/6563832/2072992/cca2502c-8d4c-11e3-819f-1b2da58ccea8.PNG)

14) Not sure if that's necessary to change but the identity supplement's description text doesn't seem to fit properly.

![beschreibung](https://f.cloud.github.com/assets/6563832/2072994/d5f068f8-8d4c-11e3-8e60-5e251cebfc17.PNG)

15) So, the change of this one depends on you. Here the localizer wrote „Arschtotzkaner“ instead of „Arstotzkaner“. „Arsch“ means „ass“ in English. In this particular conversation the entrant is quite upset that it's so difficult to get together all the required documents, so it makes sense that he swears at the Arstotzkans. I don't know if you are allowed to have such words in the game, but I have to admit that I had to smirk a bit when I read it. :)

![arschtotzkaner](https://f.cloud.github.com/assets/6563832/2072995/e21c34ae-8d4c-11e3-9588-9c17b66046fa.PNG)

16) In the bulletin of December 5th the „ä“ looks like an „a“ again. See entry 4.

![a](https://f.cloud.github.com/assets/6563832/2072999/01c5c8a6-8d4d-11e3-810c-3e51ff8e3927.PNG)

17) To me as a european the surname „Ng“ seems a bit strange. After googling it I now know that it actually exists, but it still kinda looks like some misspelled word. I guess you have to decide if you keep it or not.

![nachname ng](https://f.cloud.github.com/assets/6563832/2073001/0f262158-8d4d-11e3-8065-9ddb8ac1e5ac.PNG)

18) The issue with the disappearing dots again. If you compare the „ü“ and the „ä“ you see that the „ä“'s dots sit one pixel higher than the „ü“'s ones. If you fix that and the dotted line gets moved up one pixel, the letters don't touch the line anymore. This applies to the other affected bulletins, too. See entry 4 and 16.

![a u](https://f.cloud.github.com/assets/6563832/2073006/2ca148f2-8d4d-11e3-8c38-bae5c74a18b6.PNG)

19) The word „hat“ is located at the beginning of the sentece and therefore must be in upper case.

![hat hat](https://f.cloud.github.com/assets/6563832/2073013/35fe97ba-8d4d-11e3-9c16-ab73624d2d42.PNG)

20) The „Ü“ touches the „I“ above so it looks a bit strange. Maybe you can adjust the line spacing.

![u beruhrt i](https://f.cloud.github.com/assets/6563832/2073024/417fbbe6-8d4d-11e3-8370-f133ab504cbc.PNG)

21) This sentence doesn't make sense. The first one highlighted is actually correct, but it sounds weird in the context. I recommend changing it with „Das kann ich nicht sagen“. In the following sentence the two highlighted „in“ have to be removed, as well as the „n“ in „Tagen“.

![aufenthalt](https://f.cloud.github.com/assets/6563832/2073031/799f12b0-8d4d-11e3-898d-93d63f0b02c1.PNG)

22) Here an „n“ is missing. It should say „denn“ instead of „den“.

![den denn](https://f.cloud.github.com/assets/6563832/2073034/8c3bcc92-8d4d-11e3-8855-370b64e05619.PNG)

That's it for now. I'll finish the game soon and will post any new issues I can find. Hope I was able to help! :)

**Comment by dukope** [comment]
For the localizer: 9,10,11,12, 15, 18 ,19, 21, 22

For me: 
13: This is due to the game's simple word-wrapping and can't be fixed easily.
14: Will fix.
16: Looks like the umlauts are a pixel too high on the lowercase ä. Will see how hard it is to fix.
17: "Ng" is ok. I think it's good to have some weird names.
20: Line spacing changes are too risky at this point since they would affect all languages.

@ErdmannOle, This is really helpful! All the descriptions and especially screenshots are brilliant. But please open a new issue for any further bugs (even just typos). There's too much going on in this one.

**Comment by dukope** [comment]
Most of these are fixed in 1.1.57. Please open a new issue for anything I missed.
