### ISSUE TITLE
Small French localization error

### ISSUE THREAD

**Issue by saturnin55** [dukope/BugsPlease#22]
Small mistakes on the newspaper of dec 16th.

Should be "une" instead of "un" : 

"La sécurité de la frontière **une** fois encore remise en cause"

![2014-02-02_00001](https://f.cloud.github.com/assets/6554852/2061012/771fab42-8c3c-11e3-9187-7029fe34ca82.jpg)

Also another one, not sure if it's the font that is not printing as it should or a typo, but we see "Hucun" instead of "Aucun" on an Archive ID from the blue document to comfirm the fingerprint ID.

![2014-02-02_00004](https://f.cloud.github.com/assets/6554852/2061087/6bf3efc6-8c41-11e3-8c2a-88858cf3bc88.jpg)

**Comment by saturnin55** [comment]
oh for the blue document, I see it might be the fault of a bad communist printer after all :)

**Comment by dukope** [comment]
Paging @WordsOfMagic for un/une! The second issue is indeed due to the crappy printer :)

**Comment by WordsOfMagic** [comment]
saturnin55 is right, that a typo! :-)
Sorry about that.

**Comment by dukope** [comment]
No worries! If the code I wrote was a localization, there'd be a typo every second word. (I fixed this in the tool and synced it)

**Comment by dukope** [comment]
Fixed in 1.1.57
