### ISSUE TITLE
Doubled Cursor in Fullscreen Mode

### ISSUE THREAD

**Issue by ErdmannOle** [dukope/BugsPlease#23]
When changing the game from windowed mode to fullscreen the cursor gets doubled. Windowed mode is not affected.

Im using version 1.1.56-S in Mac OS X 10.9.1.

![img_0331](https://f.cloud.github.com/assets/6563832/2061424/4c212334-8c51-11e3-86b1-f3233beb83e9.JPG)

**Comment by dukope** [comment]
Ok, I found the problem. The fix will be in the next build. Thanks for the report!

**Comment by dukope** [comment]
Fixed in 1.1.57
