### ISSUE TITLE
Male Forename Used for Woman

### ISSUE THREAD

**Issue by ErdmannOle** [dukope/BugsPlease#28]
The male forename „Ali“ is used for a female entrant.

![ali](https://f.cloud.github.com/assets/6563832/2073272/fd674c82-8d54-11e3-90dd-c7724223a0ad.PNG)

**Comment by ErdmannOle** [comment]
I just realized this could've been posted in the Inappropriate Names section. I'll include a link to it in this comment, so it is connected at least: #1. Sorry for the inconvenience.

**Comment by dukope** [comment]
Checking wikipedia, it seems "Ali" is a valid female first name. http://en.wikipedia.org/wiki/Ali_(name)
