### ISSUE TITLE
Clock after 6pm. turns black

### ISSUE THREAD

**Issue by monodance** [dukope/BugsPlease#29]
Maybe this is not bug, but feature.
![papersplease 2014-02-04 20-55-34-84](https://f.cloud.github.com/assets/5888952/2078417/ea5d3890-8dbd-11e3-9519-97565a97cdc8.jpg)

**Comment by dukope** [comment]
This one's intended. The clock face turns black like this after 6PM to indicate that time is up and the day will end after processing this immigrant.
