### ISSUE TITLE
French localization - Weird looking text in rulebook

### ISSUE THREAD

**Issue by Tailszefox** [dukope/BugsPlease#3]
![papers1](https://f.cloud.github.com/assets/890677/2049402/9db4c24e-8a5f-11e3-813c-370c6e0f4d75.png)

In the French localization, the text "Propriété du M.D.A." is slightly weird looking, due to the "i" and "é" being too close. I don't know if it's supposed to look like that, but since, in the English version, there is no such misalignment, it may be a small issue.

Hardware info:
Windows 7 64-bits
AMD Radeon HD 6850

**Comment by dukope** [comment]
This is an unfortunate rendering of rotated, non anti-aliased text in the localization tool. I tried a few things and the only thing that works well (and doesn't break something else) is to add a space. Does this look ok, or too much like separate words?

![screen shot 2014-02-01 at 12 49 27 am](https://f.cloud.github.com/assets/5263143/2051886/9019882e-8a8f-11e3-904e-3e44d06fa59b.png)

**Comment by Tailszefox** [comment]
It certainly looks better, though I assume this will [drive kerning-aware people crazy](http://xkcd.com/1015/). Still, if it's the only way that doesn't break anything and works well, it's objectively better than having the letters stuck together.

So, yeah, I think that's a good fix, and I don't think anyone will mistake this for two separated words.

**Comment by dukope** [comment]
I'm one of those people :(

A better fix, using _STYLES_

![screen shot 2014-02-01 at 1 09 33 am](https://f.cloud.github.com/assets/5263143/2052101/343c6294-8a92-11e3-9e35-86ca9cfb0123.png)

PROPRI<span style="margin-left:-2px">&nbsp;</span>ÉTÉ DU

**Comment by Tailszefox** [comment]
Looks much better indeed. 

Out of curiosity, is the text in-game rendered using HTML and CSS, or is that just an example? That seems pretty convenient.

**Comment by dukope** [comment]
The localization tool is an html5/css app. All the in-game fonts are available there and it uses css for the (text-containing) document layouts. Documents are baked directly from the tool to images, which the game uses. The game itself has only very basic text layout capabilities. The black dots visible there are for placing in-game text at runtime.

So most of the fixed document text can benefit from "precise" css-based layout. Setting all that up and converting the original documents from a psd to html/css took forever.

**Comment by Tailszefox** [comment]
Ah, I see, thanks for your explanation. I can imagine how long it was at first to convert everything, but on the other hand, now that this bulk work is done, I assume this makes things much easier now. (Though, of course, it doesn't make things easy, just easier.)

**Comment by dukope** [comment]
I'll wait to close this until the fix is published.

**Comment by Tailszefox** [comment]
Ah, alright, my bad for closing it too soon. I should leave it to you to decide when to close issues so you can keep track of what is and isn't fixed yet. I'll keep that in mind.

**Comment by dukope** [comment]
Fixed in 1.1.56
