### ISSUE TITLE
Translation issues [Russian]

### ISSUE THREAD

**Issue by vpukhanov** [dukope/BugsPlease#30]
Hello, dukope.
I think I'll start testing from tomorrow, because I'm kinda sleepy now, but I could not resist, and looked at the translation.
The quality is pretty high - fonts are good and image are redrawn really cool. But the first minor bug is...
1. Region names doesn't match  

That's not a major bug, because it's pretty hard to translate the names, but the translated doesn't sound really good.

Obristan became Orbistan
Kolechia became Koletchia (tch instead of kh)
Republia became Republika

But that's OK, because you just can't fully transcribe region names to Russian, but

Arstotzka became Arstotia

That sounds a little funny, which I don't think communistic region name should sound.

But that's up to you, because this is just a translation and it can't be fully transcribed as I said. I'm just a little worried about how Arstotia sounds.

I'll look on it deeper tomorrow, how it feels in-game and everything like that.

**Comment by dukope** [comment]
Yeah, the region names are fairly subjective and I'm ok with most of them. I'm talking with the Russian localizers now about "Arstotia" as you're not the first to mention it.

If anyone else is playing in Russian and has an opinion about this, please drop a comment here.

**Comment by Longer** [comment]
Me like "Arstotzka" more than "Arstotia" too.

**Comment by dukope** [comment]
Ok. Is "Арстотцка" the expected transliteration of "Arstotzka"

**Comment by vpukhanov** [comment]
Yes, that's the best choice

**Comment by vpukhanov** [comment]
Two more bugs:
1. In the guidebook the words "Ministery of Admission" ("Министерство Въезда") are not centered. They are slightly shifted to left.
2. **IMPORTANT!** In the first EZIC letter (from Corman Drex) in the first sentence it's written Asrstotia ("Асрстотия") instead of Arstotia ("Арстотия")

**Comment by vpukhanov** [comment]
1. **IMPORTANT!** On the end of 11th day it says "Вбирайте" instead of "Выбирайте"

**Comment by vpukhanov** [comment]
1. **IMPORTANT!** On the end of 12th day it says "Вбирайте" instead of "Выбирайте"

**Comment by dukope** [comment]
Fixed in 1.1.58
