### ISSUE TITLE
Linux: Text cutoff?

### ISSUE THREAD

**Issue by Disk1of5** [dukope/BugsPlease#32]
Not sure if this is legit like a line distortion effect from a Dot matrix printer, but when placed over the Name or Alias text it can completely change the look of the output based off of the bitmap font used.
![papersplease](https://f.cloud.github.com/assets/2611017/2084533/bae6a8f8-8e26-11e3-9752-4245c599a158.png)

**Comment by DissCent** [comment]
Like in #12 and #19, this is by design :)

**Comment by dukope** [comment]
Yeah, this is just my crappy design. I kinda like that you have to use inspect mode sometimes to verify this. The biggest problem is that it's no consistent with the other printed docs. But at this point I'll just leave it.
