### ISSUE TITLE
Vertical sync problem

### ISSUE THREAD

**Issue by vpukhanov** [dukope/BugsPlease#34]
**NOT CRITICAL**

I don't know wether it's a problem with my videocard or beta version (but I think the latter, because the release version works good).

Sometimes I see the part of the previous and a second frame (e.x. when I'm moving guidebook). You can see two frames at a time, which usually appear if you have some problems with vertical synchronisation.

I can't take a screenshot, because on the final shot we can see only one frame, so everything looks good.

System: Windows 8.1 x64
Videocard: Nvidia GeForce 550 Ti

**Comment by dukope** [comment]
Is this in fullscreen or windowed mode? OpenFL has switched to SDL2 since the last release of the game so maybe the sync setting has changed.

**Comment by vpukhanov** [comment]
In fullscreen. I'll try it out in windowed mode in a second.

**Comment by vpukhanov** [comment]
Yep, in windowed mode everything is great

**Comment by dukope** [comment]
Ok, that definitely sounds like a vsync problem. I'll look into it, thanks.

**Comment by vpukhanov** [comment]
So, the vertical sync problem disappeared (somehow). 
But now the game freezes randomly for a second.

**Comment by vpukhanov** [comment]
I think, that it's not randomly.
It freezes then I'm clicking some interface elements (buttons or speaker for calling next immigrant)
Seems the same as #31 but not only menu buttons, but whole interface.

**Comment by vpukhanov** [comment]
So, now this problem disappeared, but vsync problem returned =) I don't know, what to think. Try to look into vertical sync, maybe that's the reason.
