### ISSUE TITLE
[Brazilian Portuguese] Button text clipping

### ISSUE THREAD

**Issue by laurolima** [dukope/BugsPlease#35]
I'm on Linux and running the software rendering version. When you press the button, large phrases on text are clipped.

![arstotzka](https://f.cloud.github.com/assets/6205344/2105951/c32b807e-8f98-11e3-91a2-2f19c774f55d.gif)

**Comment by dukope** [comment]
This'll be fixed in the next build. Thanks for the report.

**Comment by dukope** [comment]
Fixed in 1.1.58
