### ISSUE TITLE
Typos in the English version

### ISSUE THREAD

**Issue by Katecapsize** [dukope/BugsPlease#36]
Not sure if these two are intentional and meant to make the entrants sound foreign, but:
- the third person on day 1 says, "I have waited in this damn line **since for** 8 hours."
- if denied, the watch owner guy on day  21 says, "All **Arsotzkans** are same. "

**Comment by dukope** [comment]
The first one's ok, but the second one's definitely a typo. Thanks!

**Comment by dukope** [comment]
Fixed in 1.1.58
