### ISSUE TITLE
German Localization - Typos and Graphical Issues #2

### ISSUE THREAD

**Issue by ErdmannOle** [dukope/BugsPlease#38]
I checked all of my previously reported issues and here are the ones that haven't been fixed yet:

1) The approval stamp's „M“ in „Genehmigt“ still looks faulty.

![pixelfehler stempel](https://f.cloud.github.com/assets/6563832/2109645/3246c3b4-8ff4-11e3-9d81-3c8de2c0f664.PNG)

2) The „N“ in „Kolechien“ still looks like an „H“.

![kolechien](https://f.cloud.github.com/assets/6563832/2109646/39ea338a-8ff4-11e3-8ee6-a8aee9f3d5ac.PNG)

3) „Ver-rä-ter“ still gets seperated wrong.

![verrat-er verra-ter](https://f.cloud.github.com/assets/6563832/2109647/43bccd3c-8ff4-11e3-9fcb-c1e2864f3057.PNG)

4) In this EZIC document the „Ü“ still touches the „I“.

![u beruhrt i](https://f.cloud.github.com/assets/6563832/2109648/4cf61b56-8ff4-11e3-88d6-6be787b21563.PNG)

From here, all of the following issues are new.

5) In this description the word „Irokesenschnitt“ is seperated wrong. Correct would be „Irokesen-schnitt“. I think a solution could be that you write it „Irokesen-[space]schnitt“ so it gets treated as two words and therefore seperated at the right position. Unfortunately this would not work anymore as soon as the Access Permit is introduced.

![irokesenschni-tt](https://f.cloud.github.com/assets/6563832/2109654/8497f386-8ff4-11e3-8187-267d075ebadb.PNG)

6) The prompt „An Boten zurück“ could be a little more intelligible. I recommend changing it to „An Boten zurückgeben“ or something similar. This affects all EZIC messages.

![zuruck an boten](https://f.cloud.github.com/assets/6563832/2109659/9ecfdb88-8ff4-11e3-8fd3-df2a12e93dd0.PNG)

7) This section contains all cases where „Pass“ needs to be changed to „Paß“.

Bulletin of December 16th:

![pass pa 16 12](https://f.cloud.github.com/assets/6563832/2109663/ad9ea252-8ff4-11e3-8cf4-b59e6158f721.PNG)

All the passport seizure slips:

![pass pa konf](https://f.cloud.github.com/assets/6563832/2109669/c8a5b900-8ff4-11e3-8085-e36923971d71.PNG)

8) In the bulletin of December 16th, the instructions for the confiscation contain a picture with English terms. Additionally the text below doesn't really fit. The umlauts on the lower case „ä“ are slighty too high again as well.

As you can see on the right, I adjusted the id card for the German version. If you want I'll send you the file. I ensure you that it's perfectly accurate.

![pa-konfiszierung](https://f.cloud.github.com/assets/6563832/2109678/f1cfad68-8ff4-11e3-8659-f5af30f4d913.PNG)

9) While working on the confiscation document, something else caught my eye. If you compare the id card and the picture in the bulletin, you can see that the space between „Altan“ and „District“ is a lot bigger in the picture. On the id card it almost looks like it's a single word. You might want to fix this. This affects the id cards in the English and German version.

![id card blanks](https://f.cloud.github.com/assets/6563832/2109684/14724a7e-8ff5-11e3-98a8-f55aeaff5d6e.PNG)

![ausweise](https://f.cloud.github.com/assets/6563832/2109685/19829014-8ff5-11e3-8fee-a9813933f9a9.PNG)

10) A hyphen is missing in the rule book.

![bindestrich fehlt](https://f.cloud.github.com/assets/6563832/2109715/8a324a5c-8ff5-11e3-8eac-36a836813ebe.PNG)

11) I think this abbreviation doesn't make sense. I just can't think of the word that is meant by „Vertr.“. I propose to use „Konf.“ as abbreviation for „Konfiszierung“.

![vertr](https://f.cloud.github.com/assets/6563832/2109718/93b3d096-8ff5-11e3-80e4-7dd0982fab96.PNG)

12) The first sentence needs to be rearranged. It should say: „Ich habe ihn zu den Akten gelegt und kann ihn Ihnen jetzt nicht wieder aushändigen.“ Or you simply remove the penultimate word „Ihnen“.

And the word „meine“ is missing an „n“ at the end.

![pass konfisziert typo](https://f.cloud.github.com/assets/6563832/2109721/a46175c4-8ff5-11e3-8ee8-4c500cac3ae1.PNG)

13) The conversation of December 17th contains a logic issue. After bashing the son's picture on the wall, in the English version the entrant says: „Maybe he should try sports.“ But in the highlighted sentence from the German version it mistakenly says: „Maybe I should try sports.“

![sport machen](https://f.cloud.github.com/assets/6563832/2109726/ce07aee8-8ff5-11e3-8ac7-aed8e214d16f.PNG)

14) The love note contains a few spelling errors. On the third page the highlighted „T“ is redundant. In the following line the „E“ and „M“ have to be swapped so it says „Herzschmerz“. But apart from this the entire note is very difficult to read. And it doesn't even rhyme!

In the picture below you can see that I renewed the note's text so it is actually readable and now it rhymes, too. Loosely translated into English it means: „You are hot like fire's embers, I can't get enough of you, you are truly good-hearted, give me my visa.“ You have to decide if you want that to be changed. Just as before, I can provide you the graphics if you want.

![love note vergleich](https://f.cloud.github.com/assets/6563832/2109742/0c8aa1fc-8ff6-11e3-8684-e52788153712.PNG)

If the love note gets changed the entrants answer has to be adjusted accordingly.

![love note text andern](https://f.cloud.github.com/assets/6563832/2109744/166c3a8c-8ff6-11e3-8495-14d04d00fb2d.PNG)

15) In the bulletin of December 18th, I recommend changing the highlighted word with „treten“.

![sind treten](https://f.cloud.github.com/assets/6563832/2109747/290dd092-8ff6-11e3-87ec-566f06771b68.PNG)

16) In the newspaper of December 19th the umlauts of the „ä“ sit slightly too high and touch the letters above. Playing the game a little further on, it seems that this issue concerns all newspapers.

![umlaute a zeitung](https://f.cloud.github.com/assets/6563832/2109752/3bef6086-8ff6-11e3-9d80-27727c13fbef.PNG)

17) Bulletin of December 19th: The word „konzentriert“ is misspellt.

![konzentriert](https://f.cloud.github.com/assets/6563832/2109755/45ab029c-8ff6-11e3-8f95-4f6835b8995b.PNG)

18) In the Access Permit the umlauts of the „Ä“ in „Nationalität“ and „Ö“ in „Größe“ are not visible.

![umlaute nicht sichtbar](https://f.cloud.github.com/assets/6563832/2109762/6ee1733a-8ff6-11e3-9f95-04bc1b6df16e.PNG)

The same problem appears with the highlighted letters in the counterfeiter flyer on day 29:

![umlaute nicht sichtbar 02](https://f.cloud.github.com/assets/6563832/2109763/792d75a0-8ff6-11e3-976a-7615130da335.PNG)

19) In this conversation of December 21st a full stop is missing.

![punkt fehlt](https://f.cloud.github.com/assets/6563832/2109768/87464720-8ff6-11e3-8533-52dbf5c5d0ce.PNG)

20) The little girl's picture you receive on December 21st still has the English message on its back.

![madchen notiz](https://f.cloud.github.com/assets/6563832/2109774/9b123958-8ff6-11e3-9c1f-fadc51a42e54.PNG)

21) When deleting a savegame the word "vom" should be replaced by "von" since it sounds better.

![loschen vom](https://f.cloud.github.com/assets/6563832/2116212/e72985e2-9070-11e3-877b-2b1307e3867d.png)

I guess that's it. I finished the game and these are all the issues I could find. I'll check if they got removed, as soon as the next update gets released.

**Comment by dukope** [comment]
When it comes to localization, a lot of this stuff is subjective. I've fixed the stuff I could and asked the localizer to look over everything else. Here's where we're at:

1) Leaving as-is.
2) Fixed
3) Leaving as-is
4) Leaving as-is
5) Leaving as-is
6) Leaving as-is
7) Leaving as-is
8) Leaving as-is (this document is unlocalized in all languages)
9) Fixed
10) Leaving as-is
11) Leaving as-is
12) Leaving as-is
13) Fixed
14) Fixed
15) Leaving as-is
16) Fixed
17) Leaving as-is (http://www.canoo.net/services/Controller?input=konzertiert&MenuId=Search&service=canooNet&lang=de)
18) Leaving as-is
19) Fixed
20) May fix in a later update
21) Leaving as-is

Thanks again for all your help ErdmannOle

**Comment by dukope** [comment]
Fixed in 1.1.58
