### ISSUE TITLE
Logic Issue When Denying an Entrant

### ISSUE THREAD

**Issue by ErdmannOle** [dukope/BugsPlease#39]
If an entrant from United Fed doesn't have a passport on day 25 (when United Feds are not allowed to enter) the inspector still says „No entry from United Federation“ when denying. This makes no sense as the inspector can't know the entrants nationality without looking into their passport.

**Comment by Katecapsize** [comment]
Slightly similar glitch also happens on day 19 when Imporians are prohibited from entering. The first entrant is scripted to be an Imporian, but if you let them in and later deny someone else, the inspector says "Imporians are prohibited from entering" to the first denied entrant regardless of their nationality. Doesn't apply to scripted people, i.e. Jorji and the lady who recognizes the inspector.

**Comment by dukope** [comment]
How do you guys find this stuff :) 

~~(I'm gonna try fixing both of these)~~ Done.

**Comment by dukope** [comment]
Fixed in 1.1.58
