### ISSUE TITLE
Graphical oddity with an entrant

### ISSUE THREAD

**Issue by Tailszefox** [dukope/BugsPlease#5]
Image:
![papers2](https://f.cloud.github.com/assets/890677/2049385/5a6a1638-8a5f-11e3-9483-d057f84a1a6c.png)

There is a weird line in front of her glasses. I would think it is her hair, but it's not connected to her "actual" hair, it's just floating there, which makes it look really weird.

Hardware info:
Windows 7 64-bits
AMD Radeon HD 6850

**Comment by dukope** [comment]
This is a byproduct of the rough-shod technique for generating random traveler faces. I think that line is just a shadow from the nose, showing through the glasses. Looks weird but I don't have a good fix.
