### ISSUE TITLE
Graphical oddity - Overlapping issues between guard and entrant

### ISSUE THREAD

**Issue by Tailszefox** [dukope/BugsPlease#6]
![papers3](https://f.cloud.github.com/assets/890677/2049658/1adb22a4-8a65-11e3-911c-b3db60dc06da.png)

(My apologies for the bad quality, I had to take a video to capture the bug, as I couldn't manage to time my screenshots to be at the right moment.)

When arresting an entrant, if the next one is called immediately, there will be a small overlapping issue while the entrant walks to the booth. The walking entrant is shown over the bottom guard, while logically, he should be shown as being behind the guard.

**Comment by dukope** [comment]
This is an old bug that I'll keep pushing for now.
