### ISSUE TITLE
localized text alignment

### ISSUE THREAD

**Issue by schupet** [dukope/BugsPlease#8]
German localization. 
There is an odd right text alignment in the first text bubble of the 5th person on the 2nd day.

![1](https://f.cloud.github.com/assets/6552159/2051029/b9f9b26c-8a81-11e3-9cca-b824bca91577.jpg)

**Comment by dukope** [comment]
This is just how the wrapping works. Multiline dialog uses a fixed-width box. Also German has big long words that almost never wrap well.
