### ISSUE TITLE
Missing executable

### ISSUE THREAD

**Issue by LibertyPaul** [dukope/BugsPlease#9]
I have installed PP on Ubuntu 13.10, but size of downloaded content == 0, folder Steam/SteamApps/common/PapersPlease/ is empty, and when I try to launch the game steam shows me an error:
"Failed to start game (missing executable)".

**Comment by dukope** [comment]
The Linux build is only on the password-protected beta branch. If you've completed the game on another platform, email me for the password so you can test it on Linux.

**Comment by LibertyPaul** [comment]
Hmm, strange, the game appears in my library as usual.
OK, I'll send you letter.

**Comment by dukope** [comment]
Yeah that's just me not configuring Steam properly to hide the build. I'll punt on that unless it becomes a big problem.
